version: '3'

services:
  db:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    # デフォルトでは，imMemoryのオプションが付与されてしまう
    # コンテナを落としても，テーブル定義のデータを残すため
    command: -jar DynamoDBLocal.jar -dbPath ./data

  api:
    build: ./api-server
    command: go run main.go
    ports:
      - 1323:8000
