version: '3'

services:
  db:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    # デフォルトでは，imMemoryのオプションが付与されてしまう
    # コンテナを落としても，テーブル定義のデータを残すため
    volumes:
     - ./dynamodb:/data
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb

  api:
    build: ./api-server
    command: go run main.go
    volumes:
      - .:/app
    ports:
      - 1323:8000
    env_file: .env
